stages:
  clean-data:
    cmd: make elt-data
    deps:
      - powr
      - main.py
      - data/raw
    outs:
      - data/clean/data.csv

  generate-dataset:
    cmd: make generate-dataset
    deps:
      - powr
      - main.py
      - data/clean/data.csv
    outs:
      - data/dataset/train.csv
      - data/dataset/test.csv
      - data/dataset/val.csv
      - models/scaler.pkl

  train-model:
    cmd: make train-model
    deps:
      - powr
      - main.py
      - data/dataset/train.csv
      - data/dataset/test.csv
      - data/dataset/val.csv
    outs:
      - models/linear_model

  predict-powr:
    cmd: make predict-powr
    deps:
      - powr
      - main.py
      - models/linear_model
      - data/dataset/
    outs:
      - data/predictions/predictions.csv
